-- MySQL Script generated by MySQL Workbench
-- Wed Feb 12 13:39:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(445) NULL,
  PRIMARY KEY (`idarticle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idarticles` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idarticles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post_article` (
  `idUsers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `age` INT NULL,
  `email` VARCHAR(45) NULL,
  `articles_idarticles` INT NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Users_articles_idx` (`articles_idarticles` ASC) VISIBLE,
  CONSTRAINT `fk_Users_articles`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `mydb`.`users` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libros` (
  `idlibros` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `publisher` MEDIUMTEXT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idlibros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libros_has_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libros_has_articles` (
  `libros_idlibros` INT NOT NULL,
  `articles_idarticles` INT NOT NULL,
  PRIMARY KEY (`libros_idlibros`, `articles_idarticles`),
  INDEX `fk_libros_has_articles_articles1_idx` (`articles_idarticles` ASC) VISIBLE,
  INDEX `fk_libros_has_articles_libros1_idx` (`libros_idlibros` ASC) VISIBLE,
  CONSTRAINT `fk_libros_has_articles_libros1`
    FOREIGN KEY (`libros_idlibros`)
    REFERENCES `mydb`.`libros` (`idlibros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libros_has_articles_articles1`
    FOREIGN KEY (`articles_idarticles`)
    REFERENCES `mydb`.`users` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
